(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){

SupAPI.registerPlugin("typescript", "Sup.Sound", {
    code: "module Sup { export class Sound extends Asset {} }",
    defs: "declare module Sup { class Sound extends Asset { dummySoundMember; } }"
});
SupAPI.registerPlugin("typescript", "Sup.Audio", {
    code: "module Sup {\r\n  export module Audio {\r\n    export function getMasterVolume(volume) {\r\n      player.gameInstance.audio.getContext();\r\n      return player.gameInstance.audio.masterGain.gain.value;\r\n    }\r\n    export function setMasterVolume(volume) {\r\n      player.gameInstance.audio.getContext();\r\n      player.gameInstance.audio.masterGain.gain.value = volume;\r\n    }\r\n  }\r\n}",
    defs: "declare module Sup {\r\n  module Audio {\r\n    function getMasterVolume(): number;\r\n    function setMasterVolume(volume: number): void;\r\n  }\r\n}\r\n"
});
SupAPI.registerPlugin("typescript", "Sup.Audio.SoundPlayer", {
    code: "module Sup {\r\n  export module Audio {\r\n    export function playSound(pathOrAsset: string|Sound, volume=1.0, options?: { loop?: boolean; pitch?: number; pan?: number; }) {\r\n      return new SoundPlayer(pathOrAsset, volume, options).play();\r\n    }\r\n  \r\n    export class SoundPlayer {\r\n      __inner: any;\r\n      constructor(pathOrAsset: string|Sound, volume=1.0, options?: { loop?: boolean; pitch?: number; pan?: number; }) {\r\n        let audioCtx = player.gameInstance.audio.getContext();\r\n        let audioMasterGain = player.gameInstance.audio.masterGain;\r\n        let soundAsset = (typeof pathOrAsset === \"string\") ? get(pathOrAsset, Sound) : <Sound>pathOrAsset;\r\n        this.__inner = new SupEngine.SoundPlayer(audioCtx, audioMasterGain, soundAsset.__inner.buffer);\r\n        this.__inner.setVolume(volume);\r\n        \r\n        if (options != null) {\r\n          if (options.loop != null) this.__inner.setLoop(options.loop);\r\n          if (options.pan != null) this.__inner.setPan(options.pan);\r\n          if (options.pitch != null) this.__inner.setPitch(options.pitch);\r\n        }\r\n      }\r\n      play() { this.__inner.play(); return this; }\r\n      stop() { this.__inner.stop(); return this; }\r\n      pause() { this.__inner.pause(); return this; }\r\n\r\n      getLoop() { return this.__inner.isLooping; }\r\n      setLoop(looping) { this.__inner.setLoop(looping); return this; }\r\n      getVolume() { return this.__inner.volume; }\r\n      setVolume(volume) { this.__inner.setVolume(volume); return this; }\r\n      getPan() { return this.__inner.pan; }\r\n      setPan(pan) { this.__inner.setPan(pan); return this; }\r\n      getPitch() { return this.__inner.pitch; }\r\n      setPitch(pitch) { this.__inner.setPitch(pitch); return this; }\r\n    }\r\n  }\r\n}\r\n",
    defs: "declare module Sup {\r\n  module Audio {\r\n    function playSound(pathOrAsset: string|Sound, volume?: number /* 1.0 */, options?: { loop?: boolean; pitch?: number; pan?: number; }): SoundPlayer;\r\n  \r\n    class SoundPlayer {\r\n      constructor(pathOrAsset: string|Sound, volume?: number /* 1.0 */, options?: { loop?: boolean; pitch?: number; pan?: number; });\r\n      play(): SoundPlayer;\r\n      stop(): SoundPlayer;\r\n      pause(): SoundPlayer;\r\n\r\n      getLoop(): boolean;\r\n      setLoop(looping: boolean): SoundPlayer;\r\n      getVolume(): number;\r\n      setVolume(volume: number): SoundPlayer;\r\n      getPan(): number;\r\n      setPan(pan: number): SoundPlayer;\r\n      getPitch(): number;\r\n      setPitch(pitch: number): SoundPlayer;\r\n    }\r\n  }\r\n}\r\n"
});

},{}]},{},[1]);
